---
title: "Peaklocationtypegraphs_all"
output: html_document
---

Pval: Takes an Excel file with the manually collected output from the determinelocation2types (percentage of peaks in intergenic regions) and the output of hypergeometric enrichment tests for each of these (p-values). Manual input provided within this code is the percentage of the genome that is intergenic.


```{r setup, warning=FALSE,message=FALSE}
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(forcats))


Peaklocations_pval=read_excel("Mosaicslists_2types_output.xlsx")

#Providing %age of the genome that is intergenic.
Hbt_inter=13.3
Hvo_inter=15.9
Hmed_inter=15.7
Hca_inter=14.1
Ec_inter=14.2

```

Plot the data

```{r plot}

#Manually ordered, with similar species together.
#ggplot(Peaklocations_pval,aes(y=percentinter,x=fct_inorder(TF))) + geom_bar(aes(fill=Hypergeom_p),stat="identity")+geom_segment(x=0.5,xend=1.5,y=Hbt_inter,yend=Hbt_inter,colour="red",size=2,lty=6)+geom_segment(x=1.5,xend=4.5,y=Hvo_inter,yend=Hvo_inter,colour="red",size=2,lty=6)+geom_segment(x=4.5,xend=5.5,y=Hmed_inter,yend=Hmed_inter,colour="red",size=2,lty=6)+geom_segment(x=5.5,xend=7.5,y=Hca_inter,yend=Hca_inter,colour="red",size=2,lty=6)+theme_bw()+ylim(c(0,100))

#Ordered by value and output plot
#pdf("Intergenic_peaks_Mosaics-AKS.pdf",height=4,width=6)
ggplot(Peaklocations_pval,aes(y=percentinter,x=reorder(TF,percentinter))) + geom_bar(aes(fill=Hypergeom_p),stat="identity")+geom_segment(x=0.5,xend=1.5,y=Hbt_inter,yend=Hbt_inter,colour="red",size=2,lty=6) + geom_segment(x=1.5,xend=2.5,y=Hvo_inter,yend=Hvo_inter,colour="red",size=2,lty=6) + geom_segment(x=2.5,xend=3.5,y=Hca_inter,yend=Hca_inter,colour="red",size=2,lty=6) + geom_segment(x=3.5,xend=4.5,y=Hvo_inter,yend=Hvo_inter,colour="red",size=2,lty=6) + geom_segment(x=4.5,xend=5.5,y=Hca_inter,yend=Hca_inter,colour="red",size=2,lty=6) + geom_segment(x=5.5,xend=6.5,y=Hmed_inter,yend=Hmed_inter,colour="red",size=2,lty=6) + geom_segment(x=6.5,xend=7.5,y=Hvo_inter,yend=Hvo_inter,colour="red",size=2,lty=6) + geom_segment(x=7.5,xend=8.5,y=Ec_inter,yend=Ec_inter,colour="red",size=2,lty=6) + 
  theme_bw() + 
  ylim(c(0,100)) + 
  #ggtitle("Percentage of peaks in non-coding regions") + 
  xlab("Transcription Factor") + 
  ylab("Percentage intergenic") + theme(axis.text=element_text(family="sans",size=12,face="bold"),axis.text.x=element_text(angle = 25, vjust = 0.75),axis.title=element_text(family="sans",size=14,face="bold"))

#dev.off()
```



```{r session}
sessionInfo()
```