getTSSdata6 <-function(Gene_locations,csdata) {
  #Inputs are Gene_locations - a proteintable downloaded from NCBI
  #csdata = perbase sequencing depth generated by bedtools genomecov command
  #getTSSdata6 optimised for +-400bp from TSS, best for halophiles/archaea.
  #Use getTSSdata5 for +-800bp for yeast/eukaryotes.
  
  a=length(Gene_locations$Start)
  genesmatrix=matrix(data=NA,nrow=a,ncol=2)
  
  for (j in (1:a)) {
    if (Gene_locations$Strand[j]=="+") {
      genesmatrix[j,1]=Gene_locations$Start[j]
      genesmatrix[j,2]=Gene_locations$Stop[j]-Gene_locations$Start[j]
    }
    else {
      genesmatrix[j,1]=Gene_locations$Stop[j]
      genesmatrix[j,2]=Gene_locations$Start[j]-Gene_locations$Stop[j] 
    }
  }
  
  interpolated=matrix(data=NA,nrow=length(csdata$V2),ncol=2)
  interpolated[,1]=csdata$V2
  interpolated[,2]=csdata$V3
  
  TSSoutput<-matrix(data=NA,nrow=a,ncol=801)
  
  for (i in (1:a)){
    c=genesmatrix[i,1]
    b=which(interpolated[,1]==c)
    if (genesmatrix[i,2]>0) {
      TSSoutput[i,]=interpolated[(b-400):(b+400),2]
    }
    else {
      TSSoutput[i,]=interpolated[(b+400):(b-400),2]
    }
  }
  return(TSSoutput)
}