---
title: "Peaklocationtypegraphs_all"
output: html_document
---

Pval: Takes an Excel file with the manually collected output from the Annotatepeaksandclassify (percentage of peaks in promoter regions) and the output of hypergeometric enrichment tests for each of these (p-values). Manual input provided within this code is the percentage of the genome that is intergenic.


```{r setup, warning=FALSE,message=FALSE}
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(forcats))


Peaklocations_pval=read_excel("Peaklocations.xlsx",sheet="Peak_genome_pval")

#Providing %age of the genome that is intergenic.
Hbt_inter=13.3
Hvo_inter=15.9
Hmed_inter=15.7
Hca_inter=14.1

```

Plot the data

```{r plot}

ggplot(Peaklocations_pval,aes(y=Promoter_peaks,x=fct_inorder(TF)))+geom_bar(aes(fill=Hypergeom_p),stat="identity")+geom_segment(x=0.5,xend=1.5,y=Hbt_inter,yend=Hbt_inter,colour="red",size=2,lty=6)+geom_segment(x=1.5,xend=3.5,y=Hvo_inter,yend=Hvo_inter,colour="red",size=2,lty=6)+geom_segment(x=3.5,xend=5.5,y=Hmed_inter,yend=Hmed_inter,colour="red",size=2,lty=6)+geom_segment(x=5.5,xend=7.5,y=Hca_inter,yend=Hca_inter,colour="red",size=2,lty=6)+theme_bw()+ylim(c(0,100))
#Note - good design IMO

```

```{r session}
sessionInfo()
```